In [5]:
# Importação
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# Impontando a Base de Dados
df_videos = pd.read_excel('videosYT.xlsx', 'videos')
display(df_videos)

,Código Vídeo,Nº de Views,Nº de Likes,Nº de Dislikes,Nº Inscrições,Responsável,Categoria
0,1,3088,306,6,0,Daniel,Tutorial
1,2,8026,690,8,8,Lira,Webscrapping
2,3,8296,664,8,0,Lira,Automação
3,4,2534,266,5,0,Daniel,Data Science
4,5,5362,456,11,5,Lira,Data Science
5,6,5631,664,6,6,Daniel,Tutorial
6,7,1047,90,2,0,Daniel,Data Science
7,8,3277,282,7,0,Lira,Automação
8,9,3033,358,6,0,Lira,Automação
9,10,7796,826,8,8,Daniel,Data Science
10,11,2464,256,7,0,Lira,Tutorial
11,12,3967,353,12,0,Lira,Automação
12,13,1409,120,3,1,Daniel,Data Science
13,14,1702,163,3,0,Lira,Tutorial
14,15,6080,614,18,6,Lira,Data Science
15,16,5027,427,10,5,Lira,Webscrapping
16,17,3094,371,6,3,Daniel,Data Science
17,18,6639,757,7,7,Daniel,Automação
18,19,1087,104,3,1,Lira,Data Science
19,20,2335,252,2,0,Lira,Webscrapping

In [ ]:
# Gráfico de Dispersão
fig = sns.scatterplot(data=df_videos, x="Nº de Views", y="Nº de Likes", hue="Responsável", style="Responsável", palette=["red", "black"])
plt.show()

In [ ]:
# Gráfico de Dispersão(Relacional)
grafico_rel = sns.relplot(data=df_videos, x="Nº de Views", y="Nº de Likes", hue="Categoria", col="Responsável")
grafico_rel.set_titles("Responsável: {col_name}")
plt.show(grafico_rel)

In [ ]:
# Gráfico de Linha
df_inscritos = pd.read_excel("videosYT.xlsx", "Inscritos")

graf_linha = sns.lineplot(data=df_inscritos, x="Mês/Ano", y="Inscritos", color="red")
plt.show(graf_linha)

In [ ]:
# Criando Histogramas
fig = sns.displot(data=df_videos, x="Nº de Views", hue="Responsável", col="Responsável", rug=True)
plt.show(fig)

In [ ]:
# Criando uma Regressão Linear
graf_regre = sns.regplot(data=df_videos, x="Nº de Views", y="Nº de Likes")
plt.show(graf_regre)

In [ ]:
graf_regre = sns.lmplot(data=df_videos, x="Nº de Views", y="Nº de Likes", hue="Responsável", markers=['o', 'x'])
plt.show(graf_regre)